[versions]
androidPlugin = "8.2.2"
kotlinAndroid = "1.9.0"

[libraries]

[plugins]
android = { id = "com.android.application", version.ref = "androidPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }
